version: '3.0'

expectations:
  population_size: 100000

actions:

## Descriptive info on vaccinated patients

  extract_vaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated
    outputs:
      highly_sensitive:
        cohort: output/input_vaccinated.csv

  data_process_vaccinated:
    run: r:latest analysis/R/data_process_vaccinated.R
    needs: [extract_vaccinated]
    outputs:
      highly_sensitive:
        cohort: output/data/data_vaccinated.rds
        vaxdates: output/data/data_vaccinated_vax_dates.rds

  data_properties_vaccinated:
    run: r:latest analysis/R/data_properties.R output/data/data_vaccinated.rds output/data_properties
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        summary: output/data_properties/data_vaccinated*.txt

  data_summarise_vaccinated:
    run: r:latest analysis/R/data_summarise.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        summary1: output/variable_summary/categorical.txt
        summary2: output/variable_summary/numeric.txt
        summary3: output/variable_summary/date.txt
        summarytables: output/variable_summary/tables/categorical_*.csv

  vaccine_tables:
    run: r:latest analysis/R/vaccine_type.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        tables: output/vaccine_type/tables/vaccine_type_*.csv

  tte_tables:
    run: r:latest analysis/R/tte_tables.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        tables: output/tte/tables/event_rates_*.csv

  tte_plots:
    run: r:latest analysis/R/tte_plots.R
    needs: [data_process_vaccinated]
    outputs:
  #    highly_sensitive:
  #      rds: output/tte/figures/plot_*.rds
      moderately_sensitive:
        svg: output/tte/figures/plot_*.svg


  run_markdown:
    run: r:latest -e 'rmarkdown::render("rmarkdown/effectiveness_report.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [data_process_vaccinated, vaccine_tables, tte_tables, tte_plots]
    outputs:
      moderately_sensitive:
        html: output/effectiveness_report.html
